CREATE TABLE PAYROLL_SPRING_DATA_JDBC (
  ID_PAYROLL BIGINT IDENTITY(1,1) PRIMARY KEY,
  STATUS VARCHAR(255),
  BUDGET NUMERIC(10,2)
);

CREATE TABLE EMPLOYEE_SPRING_DATA_JDBC (
  ID_EMPLOYEE BIGINT IDENTITY(1,1) PRIMARY KEY,
  ID_PAYROLL BIGINT,
  SALARY NUMERIC(10,2),
  POSITION VARCHAR(255),
	CONSTRAINT payroll_id_fk FOREIGN KEY (ID_PAYROLL)
	 REFERENCES PAYROLL_SPRING_DATA_JDBC(ID_PAYROLL)
		ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE_DETAIL_SPRING_DATA_JDBC (
  ID_EMPLOYEE_DETAIL BIGINT IDENTITY(1,1) PRIMARY KEY,
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  SENIORITY INT,
  ADDRESS VARCHAR(255)
);
