CREATE TABLE PAYROLL_SPRING_DATA_JDBC (
  ID_PAYROLL BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
  STATUS VARCHAR(255),
  BUDGET DECIMAL(10,2)
);

CREATE TABLE EMPLOYEE_SPRING_DATA_JDBC (
  ID_EMPLOYEE BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
  ID_PAYROLL BIGINT UNSIGNED,
  SALARY DECIMAL(10,2),
  POSITION VARCHAR(255),
  CONSTRAINT payroll_id_fk FOREIGN KEY (ID_PAYROLL)
    REFERENCES PAYROLL_SPRING_DATA_JDBC(ID_PAYROLL)
    ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE_DETAIL_SPRING_DATA_JDBC (
  ID_EMPLOYEE_DETAIL BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  SENIORITY INTEGER,
  ADDRESS VARCHAR(255)
);