CREATE TABLE payroll_spring_data_jdbc (
  id_payroll NUMBER(38) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  status VARCHAR2(255),
  budget NUMBER(10,2)
);

CREATE TABLE employee_spring_data_jdbc (
  id_employee NUMBER(38) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  id_payroll NUMBER(38),
  salary NUMBER(10,2),
  position VARCHAR2(255),
  CONSTRAINT payroll_id_fk FOREIGN KEY (id_payroll)
    REFERENCES payroll_spring_data_jdbc(id_payroll)
    ON DELETE CASCADE
);

CREATE TABLE employee_detail_spring_data_jdbc (
  id_employee_detail NUMBER(38) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  first_name VARCHAR2(255),
  last_name VARCHAR2(255),
  seniority NUMBER(10),
  address VARCHAR2(255)
);
